apiVersion: apps/v1
kind: Deployment
metadata:
  name: scientific-conference-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scientific-conference-backend
  template:
    metadata:
      labels:
        app: scientific-conference-backend
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: scientific-conference-backend
        image: "ghcr.io/stepanse/scientific-conference-backend:main"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        ports:
        - containerPort: 8000
