apiVersion: apps/v1
kind: Deployment
metadata:
  name: scientific-conference-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scientific-conference-backend
  template:
    metadata:
      labels:
        app: scientific-conference-backend
    spec:
      containers:
      - name: scientific-conference-backend
        image: "ghcr.io/stepanse/scientific-conference-backend:main"
        imagePullPolicy: Always
        env:
          - name: DJANGO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: scientific-conference-backend-secrets
                key: DJANGO_SECRET_KEY
          - name: DJANGO_ALLOWED_HOSTS
            value: "scientific-conference-backend.tutik,scientific-conference-backend,localhost,127.0.0.1"
          - name: DJANGO_DEBUG
            value: False
            
        volumeMounts:
        - mountPath: /project/db/
          name: dbvol
        ports:
        - containerPort: 8000
      volumes:
      - name: dbvol
        persistentVolumeClaim:
          claimName: scientific-conference-be-db-pvc