---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: scientific-conference-backend-secrets
  namespace: scientific-conference
spec:
  encryptedData:
    DJANGO_SECRET_KEY: AgANxTZpsJ685WqCMvniFU18dJ9A0MPz3dzo2eWdI4/06kmmRTegJ/YA5Gfdjd1DLmN7P3+LAoySuCyWWZEZFZLh5TQnpga0bJ+WBiU4gL+CItX8mBSk7qYlKcZGL16TetNqBDN6lDSVb0pcnVCu5cGe6bxV5uq6nRDQyX2KJjKTngPUTFIfRMkDYl8hswV+cCaRz0QKyjLhITRK3ecjyhdm6WjhQ0b15PGnyuETlpV/js/1zWsU8aDmK7oNFrLjaclRC+15lfPHCkgs0B9dwF/JKMrK1mj1Rbcl9GITuz4n978o7AsKsEHlQVo42hls++++g0dLSBIPYKZKjnmL904Q07rMrqW8SGGwg+BNvvTC6RCm8d7l9KYy+hNLZvJlQ9G3+3wR85ky24ho97F8TmWac3X5DrnxjIYpYIUwn2U+7ZbFLEJFOxYYxPtKf7yIkS4PBou9CuqdWbLdojLar6gBeeRlvXwIINkmcFSuyV7NfsHkmqqrCpppA9tpg9FCRvEFfKG263UZMWmU5p5ZXG4YH7oYkwGbjuk3Ngyd3eSOy4pm6lJgNQJdcjBMNPsLXKCgafoDASRxBCgeQ2buchHRmxHVCNBChtEkcRdvLTwu+dHcKnoCRtkGFscD5LA8kcDTC47Mqtg3XXsrZcstFOrY8Z6wZ9pCC8dZSe7T4vEsde6rMqNrtgCI84/sn0Gn+8mCJpkiNj1O9yKWOOQPJsWxbRqgGZDC1jA=
  template:
    metadata:
      name: scientific-conference-backend-secrets
      namespace: scientific-conference
