---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: scientific-conference-backend-secrets
  namespace: scientific-conference
spec:
  encryptedData:
    DJANGO_SECRET_KEY: AgBhZ19dmjJITZWy6MSutbxm6E2WZ98ukE5BXTB/31r7QOzqOd9EoliLnJTnEVwjyE+cDr7DMzAMWzLDbzPocNSDErksfK0HSK3YbSPp/B/evAExfkrfiyQErb4WXQNAPL/eEUThTblARrYHf7hFr2fLvrA+UNzhUpQ+0shZpkIyhTXPJ62nQMGlUOw8vUCDdNYRkpWpudVHOOWK5EiafAoBEK/EiShBeo8VzMoGqPF+IHag+VTUFZaoAfJ1O1J0CmAk62TMJsMvHHUtY+r8wd+ar65KYUKJOjo+/ZOOMKrF9M55Kmo3HrfGYXVjYcq5wsXtLn1WIoThz8kGcgbNcVHZoNgiUlemdQdWugjA3OoELQFo93CLcOCxQV0UtA7BeB7FFF2hD7ED4ayE8ysQPo1PtN7aHE4XVGjzVdLiSRC+v3GtKTKTLrcq7UPNDHfOy3aNHL/mg2hBzmGDMOGx1twcERRiMPZ7lFq47UUZtsO5RRGXkmcIDgWHVYHNV6xoa/4fT8E5hZy0VvfiHZXQRUJuT7kGoT3hI8T6a4+s0qT9wW+nIndanmHngkV+9rloELDe5F61HXhf4xwSl4fVGGD3f10wH/Rbr3235+AXdjOIvy/suoMRPc9Vh3NbKQOwEIuBjRWIJlCZB6l7afdq95go6zEG9g0Eb4+CjR1KJN11M8XQO4rTXVMbIUlooV+ZJPO8sYbdTpJGiidMfngQ6sKGUekHGzt6yR4uMZiKORyyoGPGZXf2MjchPUuRLoq792fOwWly60lzPzaJZ8KJv9/RhVd1g3pczJYPwT/epx5NVDtX4ltSlVBUfw==
  template:
    metadata:
      name: scientific-conference-backend-secrets
      namespace: scientific-conference
