# Generated by Django 5.2.7 on 2026-04-16 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_talk_is_scheduled_alter_talk_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='abstract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talk', to='core.abstract'),
        ),
    ]
